# Generated by Django 4.2 on 2026-06-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка та модель (напр. MINI Cooper)')),
                ('year', models.IntegerField(verbose_name='Рік випуску')),
                ('price', models.IntegerField(verbose_name='Вартість ($)')),
                ('price_uah', models.IntegerField(verbose_name='Вартість (грн)')),
                ('mileage', models.IntegerField(verbose_name='Пробіг (тис. км)')),
                ('transmission', models.CharField(max_length=50, verbose_name='Коробка передач')),
                ('fuel_info', models.CharField(max_length=100, verbose_name="Пальне та об'єм (напр. Бензин, 1.6 л)")),
                ('region', models.CharField(max_length=100, verbose_name='Місто/Регіон')),
                ('image', models.ImageField(upload_to='cars_photos/', verbose_name='Фото авто')),
                ('has_checked_vin', models.BooleanField(default=True, verbose_name='Перевірений VIN')),
                ('plate_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номерний знак (напр. KA 1984 EX)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
                'ordering': ['-created_at'],
            },
        ),
    ]
