# Generated by Django 4.2 on 2026-06-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Посилання на фото авто'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Марка та модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_info',
            field=models.CharField(max_length=100, verbose_name="Пальне та об'єм"),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номерний знак'),
        ),
    ]
