# Generated by Django 4.2.30 on 2026-06-17 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_remove_car_image_remove_car_price_car_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Посилання на фото')),
                ('transport_type', models.CharField(max_length=50, verbose_name='Тип транспорту')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Рік випуску')),
                ('mileage', models.IntegerField(verbose_name='Пробіг (тис. км)')),
                ('modification', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модифікація')),
                ('location', models.CharField(max_length=150, verbose_name='Регіон / Місто')),
                ('description', models.TextField(max_length=2000, verbose_name='Опис автомобіля')),
                ('color', models.CharField(max_length=50, verbose_name='Колір')),
                ('tech_state', models.CharField(max_length=100, verbose_name='Технічний стан')),
                ('price', models.IntegerField(verbose_name='Ціна ($)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
