# Generated by Django 4.2.30 on 2026-06-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carad_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='carad',
            name='fuel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип пального'),
        ),
        migrations.AddField(
            model_name='carad',
            name='transmission',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='color',
            field=models.CharField(max_length=100, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
    ]
